[dev]
prefix = "/__dev"

[pages]
root = "./src/pages"
layout = "./src/pages/_layout.tsx"
not_found = "./src/pages/404.tsx"
error = "./src/pages/500.tsx"

[auth]
prefix = "/__auth"
route.login = "/login"
route.login_redirect = "/"

route.verify = "/verify"
route.verify_redirect = "/"

route.logout = "/logout"
route.logout_redirect = "/"

route.register = "/register"
route.register_redirect = "/auth/email-sent"
must_validate_email = true

[email]
from = "hello@phinda.com"

[password_requirements]
must_have_lowercase = true
must_have_uppercase = true
must_have_special = true
must_have_number = true
max_length = 20
min_length = 8